//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18213
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.18213.
// 
#pragma warning disable 1591

namespace CoreNetLibrary.Infraestructure.ConsoleTest.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using CoreNetLibrary.Infraestructure.WebServices.Extensions;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="IBancorRecaudoWSbinding", Namespace="http://tempuri.org/")]
    public partial class IBancorRecaudoWSservice : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConsEstadoCuentaEmpresaOperationCompleted;
        
        private System.Threading.SendOrPostCallback BloqueoEstadoCuentaEmpresaOperationCompleted;
        
        private System.Threading.SendOrPostCallback PagoEstadoCuentaEmpresaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsDetEstadoCuentaEmpresaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizacionEstCtaEmpresaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaCreditosPorClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback TranPorConfirmarAbonoCreditoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AbonoCreditoIndividualOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsHistoricoCreditosOperationCompleted;
        
        private System.Threading.SendOrPostCallback EmitaCertificadosOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public IBancorRecaudoWSservice() {
            this.Url = global::CoreNetLibrary.Infraestructure.ConsoleTest.Properties.Settings.Default.CoreNetLibrary_Infraestructure_ConsoleTest_WebReference_IBancorRecaudoWSservice;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConsEstadoCuentaEmpresaCompletedEventHandler ConsEstadoCuentaEmpresaCompleted;
        
        /// <remarks/>
        public event BloqueoEstadoCuentaEmpresaCompletedEventHandler BloqueoEstadoCuentaEmpresaCompleted;
        
        /// <remarks/>
        public event PagoEstadoCuentaEmpresaCompletedEventHandler PagoEstadoCuentaEmpresaCompleted;
        
        /// <remarks/>
        public event ConsDetEstadoCuentaEmpresaCompletedEventHandler ConsDetEstadoCuentaEmpresaCompleted;
        
        /// <remarks/>
        public event ActualizacionEstCtaEmpresaCompletedEventHandler ActualizacionEstCtaEmpresaCompleted;
        
        /// <remarks/>
        public event ConsultaCreditosPorClienteCompletedEventHandler ConsultaCreditosPorClienteCompleted;
        
        /// <remarks/>
        public event TranPorConfirmarAbonoCreditoCompletedEventHandler TranPorConfirmarAbonoCreditoCompleted;
        
        /// <remarks/>
        public event AbonoCreditoIndividualCompletedEventHandler AbonoCreditoIndividualCompleted;
        
        /// <remarks/>
        public event ConsHistoricoCreditosCompletedEventHandler ConsHistoricoCreditosCompleted;
        
        /// <remarks/>
        public event EmitaCertificadosCompletedEventHandler EmitaCertificadosCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:BancorRecaudoWSIntf-IBancorRecaudoWS#ConsEstadoCuentaEmpresa", RequestNamespace="urn:BancorRecaudoWSIntf-IBancorRecaudoWS", ResponseNamespace="urn:BancorRecaudoWSIntf-IBancorRecaudoWS")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string ConsEstadoCuentaEmpresa(string InputData) {
            object[] results = this.Invoke("ConsEstadoCuentaEmpresa", new object[] {
                        InputData});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsEstadoCuentaEmpresaAsync(string InputData) {
            this.ConsEstadoCuentaEmpresaAsync(InputData, null);
        }
        
        /// <remarks/>
        public void ConsEstadoCuentaEmpresaAsync(string InputData, object userState) {
            if ((this.ConsEstadoCuentaEmpresaOperationCompleted == null)) {
                this.ConsEstadoCuentaEmpresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsEstadoCuentaEmpresaOperationCompleted);
            }
            this.InvokeAsync("ConsEstadoCuentaEmpresa", new object[] {
                        InputData}, this.ConsEstadoCuentaEmpresaOperationCompleted, userState);
        }
        
        private void OnConsEstadoCuentaEmpresaOperationCompleted(object arg) {
            if ((this.ConsEstadoCuentaEmpresaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsEstadoCuentaEmpresaCompleted(this, new ConsEstadoCuentaEmpresaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:BancorRecaudoWSIntf-IBancorRecaudoWS#BloqueoEstadoCuentaEmpresa", RequestNamespace="urn:BancorRecaudoWSIntf-IBancorRecaudoWS", ResponseNamespace="urn:BancorRecaudoWSIntf-IBancorRecaudoWS")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string BloqueoEstadoCuentaEmpresa(string InputData) {
            object[] results = this.Invoke("BloqueoEstadoCuentaEmpresa", new object[] {
                        InputData});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BloqueoEstadoCuentaEmpresaAsync(string InputData) {
            this.BloqueoEstadoCuentaEmpresaAsync(InputData, null);
        }
        
        /// <remarks/>
        public void BloqueoEstadoCuentaEmpresaAsync(string InputData, object userState) {
            if ((this.BloqueoEstadoCuentaEmpresaOperationCompleted == null)) {
                this.BloqueoEstadoCuentaEmpresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBloqueoEstadoCuentaEmpresaOperationCompleted);
            }
            this.InvokeAsync("BloqueoEstadoCuentaEmpresa", new object[] {
                        InputData}, this.BloqueoEstadoCuentaEmpresaOperationCompleted, userState);
        }
        
        private void OnBloqueoEstadoCuentaEmpresaOperationCompleted(object arg) {
            if ((this.BloqueoEstadoCuentaEmpresaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BloqueoEstadoCuentaEmpresaCompleted(this, new BloqueoEstadoCuentaEmpresaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:BancorRecaudoWSIntf-IBancorRecaudoWS#PagoEstadoCuentaEmpresa", RequestNamespace="urn:BancorRecaudoWSIntf-IBancorRecaudoWS", ResponseNamespace="urn:BancorRecaudoWSIntf-IBancorRecaudoWS")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string PagoEstadoCuentaEmpresa(string InputData) {
            object[] results = this.Invoke("PagoEstadoCuentaEmpresa", new object[] {
                        InputData});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PagoEstadoCuentaEmpresaAsync(string InputData) {
            this.PagoEstadoCuentaEmpresaAsync(InputData, null);
        }
        
        /// <remarks/>
        public void PagoEstadoCuentaEmpresaAsync(string InputData, object userState) {
            if ((this.PagoEstadoCuentaEmpresaOperationCompleted == null)) {
                this.PagoEstadoCuentaEmpresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPagoEstadoCuentaEmpresaOperationCompleted);
            }
            this.InvokeAsync("PagoEstadoCuentaEmpresa", new object[] {
                        InputData}, this.PagoEstadoCuentaEmpresaOperationCompleted, userState);
        }
        
        private void OnPagoEstadoCuentaEmpresaOperationCompleted(object arg) {
            if ((this.PagoEstadoCuentaEmpresaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PagoEstadoCuentaEmpresaCompleted(this, new PagoEstadoCuentaEmpresaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:BancorRecaudoWSIntf-IBancorRecaudoWS#ConsDetEstadoCuentaEmpresa", RequestNamespace="urn:BancorRecaudoWSIntf-IBancorRecaudoWS", ResponseNamespace="urn:BancorRecaudoWSIntf-IBancorRecaudoWS")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string ConsDetEstadoCuentaEmpresa(string InputData) {
            object[] results = this.Invoke("ConsDetEstadoCuentaEmpresa", new object[] {
                        InputData});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsDetEstadoCuentaEmpresaAsync(string InputData) {
            this.ConsDetEstadoCuentaEmpresaAsync(InputData, null);
        }
        
        /// <remarks/>
        public void ConsDetEstadoCuentaEmpresaAsync(string InputData, object userState) {
            if ((this.ConsDetEstadoCuentaEmpresaOperationCompleted == null)) {
                this.ConsDetEstadoCuentaEmpresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsDetEstadoCuentaEmpresaOperationCompleted);
            }
            this.InvokeAsync("ConsDetEstadoCuentaEmpresa", new object[] {
                        InputData}, this.ConsDetEstadoCuentaEmpresaOperationCompleted, userState);
        }
        
        private void OnConsDetEstadoCuentaEmpresaOperationCompleted(object arg) {
            if ((this.ConsDetEstadoCuentaEmpresaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsDetEstadoCuentaEmpresaCompleted(this, new ConsDetEstadoCuentaEmpresaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:BancorRecaudoWSIntf-IBancorRecaudoWS#ActualizacionEstCtaEmpresa", RequestNamespace="urn:BancorRecaudoWSIntf-IBancorRecaudoWS", ResponseNamespace="urn:BancorRecaudoWSIntf-IBancorRecaudoWS")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string ActualizacionEstCtaEmpresa(string InputData) {
            object[] results = this.Invoke("ActualizacionEstCtaEmpresa", new object[] {
                        InputData});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizacionEstCtaEmpresaAsync(string InputData) {
            this.ActualizacionEstCtaEmpresaAsync(InputData, null);
        }
        
        /// <remarks/>
        public void ActualizacionEstCtaEmpresaAsync(string InputData, object userState) {
            if ((this.ActualizacionEstCtaEmpresaOperationCompleted == null)) {
                this.ActualizacionEstCtaEmpresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizacionEstCtaEmpresaOperationCompleted);
            }
            this.InvokeAsync("ActualizacionEstCtaEmpresa", new object[] {
                        InputData}, this.ActualizacionEstCtaEmpresaOperationCompleted, userState);
        }
        
        private void OnActualizacionEstCtaEmpresaOperationCompleted(object arg) {
            if ((this.ActualizacionEstCtaEmpresaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizacionEstCtaEmpresaCompleted(this, new ActualizacionEstCtaEmpresaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:BancorRecaudoWSIntf-IBancorRecaudoWS#ConsultaCreditosPorCliente", RequestNamespace="urn:BancorRecaudoWSIntf-IBancorRecaudoWS", ResponseNamespace="urn:BancorRecaudoWSIntf-IBancorRecaudoWS")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string ConsultaCreditosPorCliente(string InputData) {
            object[] results = this.Invoke("ConsultaCreditosPorCliente", new object[] {
                        InputData});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaCreditosPorClienteAsync(string InputData) {
            this.ConsultaCreditosPorClienteAsync(InputData, null);
        }
        
        /// <remarks/>
        public void ConsultaCreditosPorClienteAsync(string InputData, object userState) {
            if ((this.ConsultaCreditosPorClienteOperationCompleted == null)) {
                this.ConsultaCreditosPorClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaCreditosPorClienteOperationCompleted);
            }
            this.InvokeAsync("ConsultaCreditosPorCliente", new object[] {
                        InputData}, this.ConsultaCreditosPorClienteOperationCompleted, userState);
        }
        
        private void OnConsultaCreditosPorClienteOperationCompleted(object arg) {
            if ((this.ConsultaCreditosPorClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaCreditosPorClienteCompleted(this, new ConsultaCreditosPorClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:BancorRecaudoWSIntf-IBancorRecaudoWS#TranPorConfirmarAbonoCredito", RequestNamespace="urn:BancorRecaudoWSIntf-IBancorRecaudoWS", ResponseNamespace="urn:BancorRecaudoWSIntf-IBancorRecaudoWS")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string TranPorConfirmarAbonoCredito(string InputData) {
            object[] results = this.Invoke("TranPorConfirmarAbonoCredito", new object[] {
                        InputData});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TranPorConfirmarAbonoCreditoAsync(string InputData) {
            this.TranPorConfirmarAbonoCreditoAsync(InputData, null);
        }
        
        /// <remarks/>
        public void TranPorConfirmarAbonoCreditoAsync(string InputData, object userState) {
            if ((this.TranPorConfirmarAbonoCreditoOperationCompleted == null)) {
                this.TranPorConfirmarAbonoCreditoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTranPorConfirmarAbonoCreditoOperationCompleted);
            }
            this.InvokeAsync("TranPorConfirmarAbonoCredito", new object[] {
                        InputData}, this.TranPorConfirmarAbonoCreditoOperationCompleted, userState);
        }
        
        private void OnTranPorConfirmarAbonoCreditoOperationCompleted(object arg) {
            if ((this.TranPorConfirmarAbonoCreditoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TranPorConfirmarAbonoCreditoCompleted(this, new TranPorConfirmarAbonoCreditoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:BancorRecaudoWSIntf-IBancorRecaudoWS#AbonoCreditoIndividual", RequestNamespace="urn:BancorRecaudoWSIntf-IBancorRecaudoWS", ResponseNamespace="urn:BancorRecaudoWSIntf-IBancorRecaudoWS")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string AbonoCreditoIndividual(string InputData) {
            object[] results = this.Invoke("AbonoCreditoIndividual", new object[] {
                        InputData});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AbonoCreditoIndividualAsync(string InputData) {
            this.AbonoCreditoIndividualAsync(InputData, null);
        }
        
        /// <remarks/>
        public void AbonoCreditoIndividualAsync(string InputData, object userState) {
            if ((this.AbonoCreditoIndividualOperationCompleted == null)) {
                this.AbonoCreditoIndividualOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAbonoCreditoIndividualOperationCompleted);
            }
            this.InvokeAsync("AbonoCreditoIndividual", new object[] {
                        InputData}, this.AbonoCreditoIndividualOperationCompleted, userState);
        }
        
        private void OnAbonoCreditoIndividualOperationCompleted(object arg) {
            if ((this.AbonoCreditoIndividualCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AbonoCreditoIndividualCompleted(this, new AbonoCreditoIndividualCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:BancorRecaudoWSIntf-IBancorRecaudoWS#ConsHistoricoCreditos", RequestNamespace="urn:BancorRecaudoWSIntf-IBancorRecaudoWS", ResponseNamespace="urn:BancorRecaudoWSIntf-IBancorRecaudoWS")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string ConsHistoricoCreditos(string InputData) {
            object[] results = this.Invoke("ConsHistoricoCreditos", new object[] {
                        InputData});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsHistoricoCreditosAsync(string InputData) {
            this.ConsHistoricoCreditosAsync(InputData, null);
        }
        
        /// <remarks/>
        public void ConsHistoricoCreditosAsync(string InputData, object userState) {
            if ((this.ConsHistoricoCreditosOperationCompleted == null)) {
                this.ConsHistoricoCreditosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsHistoricoCreditosOperationCompleted);
            }
            this.InvokeAsync("ConsHistoricoCreditos", new object[] {
                        InputData}, this.ConsHistoricoCreditosOperationCompleted, userState);
        }
        
        private void OnConsHistoricoCreditosOperationCompleted(object arg) {
            if ((this.ConsHistoricoCreditosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsHistoricoCreditosCompleted(this, new ConsHistoricoCreditosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:BancorRecaudoWSIntf-IBancorRecaudoWS#EmitaCertificados", RequestNamespace="urn:BancorRecaudoWSIntf-IBancorRecaudoWS", ResponseNamespace="urn:BancorRecaudoWSIntf-IBancorRecaudoWS")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        [UTF8EncoderExtension]
        public string EmitaCertificados(string InputData) {
            object[] results = this.Invoke("EmitaCertificados", new object[] {
                        InputData});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EmitaCertificadosAsync(string InputData) {
            this.EmitaCertificadosAsync(InputData, null);
        }
        
        /// <remarks/>
        public void EmitaCertificadosAsync(string InputData, object userState) {
            if ((this.EmitaCertificadosOperationCompleted == null)) {
                this.EmitaCertificadosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEmitaCertificadosOperationCompleted);
            }
            this.InvokeAsync("EmitaCertificados", new object[] {
                        InputData}, this.EmitaCertificadosOperationCompleted, userState);
        }
        
        private void OnEmitaCertificadosOperationCompleted(object arg) {
            if ((this.EmitaCertificadosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EmitaCertificadosCompleted(this, new EmitaCertificadosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void ConsEstadoCuentaEmpresaCompletedEventHandler(object sender, ConsEstadoCuentaEmpresaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsEstadoCuentaEmpresaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsEstadoCuentaEmpresaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void BloqueoEstadoCuentaEmpresaCompletedEventHandler(object sender, BloqueoEstadoCuentaEmpresaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BloqueoEstadoCuentaEmpresaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BloqueoEstadoCuentaEmpresaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void PagoEstadoCuentaEmpresaCompletedEventHandler(object sender, PagoEstadoCuentaEmpresaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PagoEstadoCuentaEmpresaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PagoEstadoCuentaEmpresaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void ConsDetEstadoCuentaEmpresaCompletedEventHandler(object sender, ConsDetEstadoCuentaEmpresaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsDetEstadoCuentaEmpresaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsDetEstadoCuentaEmpresaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void ActualizacionEstCtaEmpresaCompletedEventHandler(object sender, ActualizacionEstCtaEmpresaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizacionEstCtaEmpresaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizacionEstCtaEmpresaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void ConsultaCreditosPorClienteCompletedEventHandler(object sender, ConsultaCreditosPorClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaCreditosPorClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaCreditosPorClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void TranPorConfirmarAbonoCreditoCompletedEventHandler(object sender, TranPorConfirmarAbonoCreditoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TranPorConfirmarAbonoCreditoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TranPorConfirmarAbonoCreditoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void AbonoCreditoIndividualCompletedEventHandler(object sender, AbonoCreditoIndividualCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AbonoCreditoIndividualCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AbonoCreditoIndividualCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void ConsHistoricoCreditosCompletedEventHandler(object sender, ConsHistoricoCreditosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsHistoricoCreditosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsHistoricoCreditosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void EmitaCertificadosCompletedEventHandler(object sender, EmitaCertificadosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EmitaCertificadosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EmitaCertificadosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591